### ISSUE TITLE
合流したいのですが，どうやればよいでしょう．

### ISSUE THREAD

**Issue by tikegami-mw** [NLP100-MATLAB/nlp-100-exercise-by-matlab#9]
こんにちは．池上です．

ここでの記述に気がつかずに，独自に1－4章やってしまいました．（とりあえず勉強のために全部やるつもりではいるのですが）このあとどーするのが良いでしょう．

（あと，Gitも不慣れなので，何か良い参考書とかありますか？）

**Comment by minoue-xx** [comment]
ご連絡ありがとうございます。
今のところ 7,8,9 章に立候補して頂いている方がいらっしゃらないので、「これやります」とコメント頂ければ私の方で README.md に追記しておきます。

Git についてはまた別途ご連絡しますが、MATLAB からも操作できる方法を解説した以下の記事がまず参考になるかと思います。
https://qiita.com/kennykogure/items/5ac71b58e560f56f5977
https://qiita.com/stozaki/items/757b3fa687016a14a0a1
